### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by nfischer** [moll/vim-node#32]
This is a follow up to the discussion on #31. Travis currently has errors during the installation process. I saw some improved results (but still some build errors) by using this yaml file:

```yaml
language: ruby
rvm:
  - 2.1.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y vim-gtk
install: bundle install --deployment --without development
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: xvfb-run make test
```

The `apt-get` commands are the main thing that made a difference (it seemed to be able to find the `vim-gtk` package this way). The error I saw looked like this:

```
$ sudo apt-get update -qq
$ sudo apt-get install -y vim-gtk
...
$ bundle install --deployment --without development
Fetching gem metadata from https://rubygems.org/.........
Fetching https://github.com/moll/vimrunner.git
Using minitest 4.7.5
NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing
vimrunner (0.3.0), and Bundler cannot
continue.
Make sure that `gem install vimrunner -v
'0.3.0'` succeeds before bundling.

The command "bundle install --deployment --without development" failed and exited with 5 during .

Your build has been stopped.
```
